name: SkyMine
version: '${project.version}'
main: com.amirparsa.skymine.SkyMine
api-version: '1.16'

softdepend: [PlaceholderAPI]

commands:
  addmagicore:
    usage: /<command> player amount
    description: Admin Command! Add Magic Ore To A Player
    permission: iransky.admin
  customitem:
    usage: /<command> item level magical
    description: Admin Command! Add An Item To A Player
    permission: iransky.admin